# Generated by Django 5.1.15 on 2026-09-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiverRace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "season_id",
                    models.PositiveIntegerField(
                        help_text="Identificador de la temporada de Clash Royale"
                    ),
                ),
                (
                    "section_index",
                    models.PositiveIntegerField(
                        help_text="Índice de semana o tramo de la carrera (0-4)"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="matched", help_text="Estado devuelto por la API", max_length=32
                    ),
                ),
                (
                    "clan_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Puntos de fama o medallas acumuladas del clan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="river_races",
                        to="clans.clan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrera Fluvial",
                "verbose_name_plural": "Carreras Fluviales",
                "ordering": ["-season_id", "-section_index"],
            },
        ),
        migrations.CreateModel(
            name="WarDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(help_text="Fecha calendario de la jornada")),
                (
                    "day_index",
                    models.PositiveSmallIntegerField(
                        help_text="Índice dentro de la semana (0 a 6)"
                    ),
                ),
                (
                    "day_type",
                    models.CharField(
                        choices=[("training", "Entrenamiento"), ("war", "Guerra")],
                        default="training",
                        max_length=16,
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la jornada ya fue evaluada por el motor de gobernanza",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "river_race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="war_days",
                        to="wars.riverrace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jornada de Guerra",
                "verbose_name_plural": "Jornadas de Guerra",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WarAttackLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "attacks_used",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Ataques usados en la jornada (0-4)"
                    ),
                ),
                ("decks_used", models.PositiveSmallIntegerField(default=0)),
                ("medals_earned", models.PositiveIntegerField(default=0)),
                (
                    "boat_attacks_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Ataques ilegales o dirigidos a barcos enemigos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attack_logs",
                        to="clans.member",
                    ),
                ),
                (
                    "war_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attack_logs",
                        to="wars.warday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Ataque",
                "verbose_name_plural": "Registros de Ataques",
                "ordering": ["-war_day__date", "-medals_earned"],
            },
        ),
        migrations.AddConstraint(
            model_name="riverrace",
            constraint=models.UniqueConstraint(
                fields=("clan", "season_id", "section_index"), name="unique_clan_season_section"
            ),
        ),
        migrations.AddConstraint(
            model_name="warday",
            constraint=models.UniqueConstraint(
                fields=("river_race", "date"), name="unique_race_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="warattacklog",
            constraint=models.UniqueConstraint(
                fields=("war_day", "member"), name="unique_warday_member_log"
            ),
        ),
    ]
