# Generated by Django 5.1.15 on 2026-10-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riverrace",
            name="standings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ranking y puntos acumulados de los clanes rivales en la carrera",
            ),
        ),
    ]
