# Generated by Django 5.1.15 on 2026-10-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wars", "0002_riverrace_standings"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="warday",
            constraint=models.UniqueConstraint(
                fields=("river_race", "day_index"), name="unique_race_day_index"
            ),
        ),
    ]
