# Generated by Django 5.1.15 on 2026-09-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "tag",
                    models.CharField(
                        help_text="Tag del clan (ej. #2PP)",
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "medal_threshold",
                    models.PositiveIntegerField(
                        default=2000,
                        help_text="Umbral mínimo de medallas para considerar participación exitosa",
                    ),
                ),
                (
                    "war_day_reset_time",
                    models.TimeField(
                        default="10:00:00",
                        help_text="Hora de reinicio de la jornada de guerra en horario UTC",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Clan",
                "verbose_name_plural": "Clanes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "tag",
                    models.CharField(
                        help_text="Tag del jugador (ej. #PLAYERTAG)",
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("leader", "Líder"),
                            ("coLeader", "Colíder"),
                            ("elder", "Veterano"),
                            ("member", "Miembro"),
                        ],
                        default="member",
                        max_length=32,
                    ),
                ),
                (
                    "reliability_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Puntuación de fiabilidad histórica del jugador (0.00 a 100.00)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="clans.clan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro",
                "verbose_name_plural": "Miembros",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WarPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="war_passes",
                        to="clans.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pase de Guerra",
                "verbose_name_plural": "Pases de Guerra",
                "ordering": ["-start_date"],
            },
        ),
    ]
