# Generated by Django 5.1.15 on 2026-09-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("console", "Consola / Logs"),
                            ("discord_webhook", "Discord Webhook"),
                            ("telegram", "Telegram Bot"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuración del canal (webhook_url, chat_id, token, etc.)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channels",
                        to="clans.clan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal de Notificación",
                "verbose_name_plural": "Canales de Notificación",
                "ordering": ["clan", "provider"],
            },
        ),
    ]
