# Generated by Django 5.1.15 on 2026-10-05 06:18

import django.db.models.deletion
from django.db import migrations, models


def populate_default_preferences(apps, schema_editor):
    Clan = apps.get_model("clans", "Clan")
    WarAlertPreference = apps.get_model("notifications", "WarAlertPreference")
    for clan in Clan.objects.all():
        WarAlertPreference.objects.get_or_create(
            clan=clan,
            defaults={
                "is_enabled": True,
                "frequency": "hourly",
                "custom_hours": "6,7,8,9,10",
                "silence_if_zero_pending": True,
                "send_congratulations_at_close": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("clans", "0002_member_donations_member_donations_received_and_more"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarAlertPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Activa o pausa las alertas automáticas de guerra para este clan.",
                        verbose_name="Alertas activadas",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            (
                                "hourly",
                                "Cada 1 hora — 4h, 3h, 2h, 1h antes del cierre y al cierre (06:00, 07:00, 08:00, 09:00, 10:00 UTC)",
                            ),
                            (
                                "every_2h",
                                "Cada 2 horas — 4h y 2h antes del cierre y al cierre (06:00, 08:00, 10:00 UTC)",
                            ),
                            (
                                "last_2h",
                                "Últimas 2 horas — 2h y 1h antes del cierre y al cierre (08:00, 09:00, 10:00 UTC)",
                            ),
                            (
                                "last_1h",
                                "Solo última hora — 1h antes del cierre y al cierre (09:00, 10:00 UTC)",
                            ),
                            (
                                "at_close_only",
                                "Solo al cierre — 10:00 UTC (revisión y felicitación final)",
                            ),
                            ("custom", "Personalizado — Especificar lista de horas UTC exactas"),
                        ],
                        default="hourly",
                        help_text="Frecuencia con la que se enviarán las alertas automáticas de ataques pendientes.",
                        max_length=32,
                        verbose_name="Frecuencia de recordatorios",
                    ),
                ),
                (
                    "custom_hours",
                    models.CharField(
                        blank=True,
                        default="6,7,8,9,10",
                        help_text="Aplica únicamente si se elige 'Personalizado'. Lista de horas UTC separadas por comas (ej. 6,7,8,9,10).",
                        max_length=128,
                        verbose_name="Horas UTC personalizadas",
                    ),
                ),
                (
                    "silence_if_zero_pending",
                    models.BooleanField(
                        default=True,
                        help_text="Evita enviar mensajes en horas intermedias (06:00 - 09:00 UTC) si todos los miembros completaron sus ataques.",
                        verbose_name="Silencio si 0 pendientes",
                    ),
                ),
                (
                    "send_congratulations_at_close",
                    models.BooleanField(
                        default=True,
                        help_text="Envía mensaje de felicitación de 100% de asistencia a las 10:00 UTC si no hay miembros pendientes.",
                        verbose_name="Felicitar al cierre si 0 pendientes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="war_alert_preference",
                        to="clans.clan",
                        verbose_name="Clan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de Alertas de Guerra",
                "verbose_name_plural": "Preferencias de Alertas de Guerra",
                "ordering": ["clan"],
            },
        ),
        migrations.RunPython(populate_default_preferences, reverse_code=migrations.RunPython.noop),
    ]
