# Generated by Django 5.1.15 on 2026-09-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clans", "0001_initial"),
        ("wars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RosterAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("promote_elder", "Ascenso a Veterano"),
                            ("demote_member", "Degradación a Miembro"),
                            ("kick", "Expulsión del Clan"),
                            ("leadership_notice", "Aviso Informativo de Liderazgo"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de Ejecución"),
                            ("executed", "Confirmado en el Juego"),
                            ("dismissed", "Descartado por Líder"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Motivo o detalle de la infracción o mérito"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_actions",
                        to="clans.clan",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_actions",
                        to="clans.member",
                    ),
                ),
                (
                    "war_day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roster_actions",
                        to="wars.warday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acción de Roster",
                "verbose_name_plural": "Acciones de Roster",
                "ordering": ["-created_at"],
            },
        ),
    ]
